# Generated by Django 5.1.7 on 2025-04-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_academic_year_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni'), ('coordinator', 'Alumni Coordinator')], max_length=20),
        ),
    ]
