# Generated by Django 5.1.7 on 2025-04-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_pdfreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFReport',
        ),
    ]
