# Generated by Django 5.1.7 on 2025-04-25 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_pdfreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validregisternumber',
            old_name='number',
            new_name='register_number',
        ),
    ]
