# Generated by Django 5.1.7 on 2025-04-22 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_galleryitem_delete_mediaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=5),
        ),
    ]
